### PR TITLE
master

### PR DESCRIPTION
**Pull request by Rocio01**

### CODE REVIEW

**Comment by Rocio01** [comment]
Greetings 
this is a closed pull request, where we move all our changes from the development branch to the main/master branch.
Kind regards

**Comment by mimipeshy** [comment]
### STATUS :INVALID :red_circle: :recycle: 

#### Hey team @Rocio01 and @karthykarthick good job so far, but I have to mark this PR as invalid. The reason being you merged the project to master before it was reviewed,  this violates the GitHub workflow. Kindly submit another review with a PR that is open.

That's all :smile: , submit another review when done.
If you have any questions, kindly send me a message on slack and i will be glad to help

Regards
Peris Ndanu

**Comment by Rocio01** [comment]
Greetings
Thanks for the feedback, but in the requirements for Milestone 8: Deploy your app to Heroku, says ( Therefore for this milestone submission, you should add a link to the Pull Request that moves all your changes from the development branch to the main/master branch (and it should be merged by you already). Your code reviewer will double-check if your app was successfully deployed.)
Thanks for the attention 
kind regards

**Review by andresporras3423 — COMMENTED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Zulma Rocio Martinez Guarin & Karthick Harimoorthy** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

**Pull request merged**
